debug: true

server:
  port: 8080

postgresql:
  uri: "host=49.235.43.230 user=postgres password=fR7!Qx9@M#2Lk$W^8pZ&Sa dbname=intehub port=4432 sslmode=disable TimeZone=Asia/Shanghai"

jwt:
  secret: "your-secret-key-change-in-production"
