// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

// Injectors from wire.go:

func NewServer() (*Server, error) {
	config := MustProvideConfig()
	db := MustProvidePostgreSQLDB(config)
	authService := ProvideAuthService(db, config)
	handler := ProvideAuthHandler(authService)
	appService := ProvideAppService(db)
	appHandler := ProvideAppHandler(appService)
	pushService := ProvidePushService(db)
	pushHandler := ProvidePushHandler(pushService)
	fieldService := ProvideFieldService(db)
	fieldHandler := ProvideFieldHandler(fieldService)
	systemService := ProvideSystemService(db)
	systemHandler := ProvideSystemHandler(systemService)
	scheduleService := ProvideScheduleService(db)
	scheduleHandler := ProvideScheduleHandler(scheduleService)
	appContext := &AppContext{
		Config:          config,
		DB:              db,
		AuthHandler:     handler,
		AppHandler:      appHandler,
		PushHandler:     pushHandler,
		FieldHandler:    fieldHandler,
		SystemHandler:   systemHandler,
		ScheduleHandler: scheduleHandler,
	}
	server := NewServerWire(appContext)
	return server, nil
}
