-- 删除所有表（谨慎使用！）
-- 按照依赖关系的逆序删除

DROP TABLE IF EXISTS schedule_logs CASCADE;
DROP TABLE IF EXISTS schedule_tasks CASCADE;
DROP TABLE IF EXISTS workflow_logs CASCADE;
DROP TABLE IF EXISTS workflows CASCADE;
DROP TABLE IF EXISTS config_field_relations CASCADE;
DROP TABLE IF EXISTS push_histories CASCADE;
DROP TABLE IF EXISTS push_configs CASCADE;
DROP TABLE IF EXISTS field_schemas CASCADE;
DROP TABLE IF EXISTS app_configs CASCADE;
DROP TABLE IF EXISTS app_templates CASCADE;
DROP TABLE IF EXISTS app_logs CASCADE;
DROP TABLE IF EXISTS apps CASCADE;
DROP TABLE IF EXISTS system_logs CASCADE;
DROP TABLE IF EXISTS menus CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
